name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Copy the code from the repo to the Ubuntu server.
      - name: Checkout code
        uses: actions/checkout@v4

      # A small test step to see if it works.
      - name: Say hello
        run: echo "Das Grundgerüst steht! Zeit für Docker..."